name: LIQYAPP
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
    sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  cupertino_icons: ^1.0.6
  geolocator: ^10.1.0
  internet_connection_checker: ^1.0.0+1
  provider: ^6.1.1
  app_settings: ^5.1.1  
  barcode_widget: ^2.0.4
  package_info: ^2.0.2
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.4
  speech_to_text: ^6.4.1
  badges: ^3.1.2
  image: ^4.1.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.2
  location: ^5.0.3
  html: ^0.15.4
  intl: ^0.18.1
  permission_handler: ^11.1.0
  barcode_scan2: ^4.3.0
  pdf: ^3.10.6
  flutter_launcher_icons: ^0.13.1
  auto_size_text: ^3.0.0
  advance_pdf_viewer2: ^2.0.5+1
  image_cropper: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # c
  image_path_android: "assets/logo/ico_android.png"
  image_path_ios: "assets/logo/ico_ios.png"
  adaptive_icon_background: "#184093" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/logo/ico_android_adaptative.png" # only available for Android 8.0 devices and above
  background_color_ios: "#184093"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

# To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/gif/
   - assets/icons/

  fonts:
    - family: Light
      fonts:
        - asset: fonts/DaxlinePro-Light.ttf
    - family: Regular
      fonts:
        - asset: fonts/DaxlinePro-Regular.ttf
    - family: Medium
      fonts:
        - asset: fonts/DaxlinePro-Medium.ttf
    - family: Custom
      fonts:
        - asset: fonts/DaxlinePro-Bold.ttf